# Generated by Django 3.1.2 on 2020-11-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='activate',
            new_name='active',
        ),
    ]
