# Generated by Django 3.1.2 on 2020-11-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingPostCode',
            new_name='billingPostcode',
        ),
    ]
